FROM alpine
RUN apk add py3-pip build-base python3-dev libffi-dev openssl-dev haproxy nginx
RUN mkdir -p /opt/api && mkdir -p /etc/haproxy/logs
ADD errors /etc/haproxy/errors
WORKDIR /opt/api
ADD api/requirements.txt /opt/api
RUN pip3 install --no-cache-dir -r requirements.txt
ADD api/. /opt/api
ADD ./docker-entrypoint.sh /bin/docker-entrypoint
RUN chmod +x /bin/docker-entrypoint 
ADD ./haproxy.conf /etc/haproxy/haproxy.cfg
EXPOSE 80
CMD ["/bin/docker-entrypoint"]
