apiVersion: v1
kind: Service
metadata:
  name: my-service1
  labels:
    app: front
spec:
  type: NodePort
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80